### PR TITLE
some improvments

### PR DESCRIPTION
**Pull request by tihomirocrew**
added marker teleport

### CODE REVIEW

**Comment by aci1337** [comment]
Hello i will take a look in it!!

**Comment by tihomirocrew** [comment]
add this https://github.com/aci1337/samp-cheat/pull/2/commits/68b312aa123827704766b1f30e5406e7a9e6a07c

**Comment by aci1337** [comment]
sure! Give me just some time, i am right now working on something else way more important atm

**Comment by aci1337** [comment]
Added

**Comment by aci1337** [comment]
you can now use it. It has been added and modified! It works on every server including OG-TIMES and RPG.B-HOOD.RO!

**Comment by tihomirocrew** [comment]
fix fly function https://raw.githubusercontent.com/Stickey21/Stealth-Remastered/origin/Stealth%20Remastered/Features/Combat.cpp

**Comment by aci1337** [comment]
I will, soon today.

**Pull request closed without merging**
